version: '3.8'
services:
  backend:
    build:
      context: ./jacaclub-backend
      dockerfile: Dockerfile
    container_name: jacaclub-backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./jacaclub-frontend
      dockerfile: Dockerfile
    container_name: jacaclub-frontend
    ports:
      - "3000:3000"
volumes:
  mongo-data:
